import type { Metadata } from "next";
import { SiteFooter } from "@/app/components/SiteFooter";
import { SiteHeader } from "@/app/components/SiteHeader";

export const metadata: Metadata = { title: "Website Terms", description: "Terms for use of the Luna Sol Group website and public decision tools.", alternates: { canonical: "/terms" } };

export default function TermsPage() {
  return <><SiteHeader /><main id="main" className="trust-page"><header><div className="shell"><span>Trust center</span><h1>Website terms</h1><p>Conditions for using this website, its public content, and its decision tools.</p></div></header><article className="shell trust-article"><p className="trust-note"><strong>Effective August 12, 2026.</strong> These are website-use terms, not consulting engagement terms.</p><section><h2>Informational use</h2><p>Website content and Operations Lab tools are provided for general informational and decision-structuring purposes. They do not constitute legal, financial, accounting, safety, regulatory, investment, or other professional advice, and they do not replace direct operating evidence or executive judgment.</p></section><section><h2>No client relationship</h2><p>Using the site, submitting an inquiry, or receiving a response does not create a consulting or fiduciary relationship. An engagement begins only through a separate written agreement.</p></section><section><h2>Models and outputs</h2><p>Public tools use disclosed assumptions and may produce incomplete or unsuitable outputs when inputs are inaccurate or the real operating system differs from the model. Users remain responsible for validating all assumptions, data, constraints, and decisions.</p></section><section><h2>Evidence and attribution</h2><p>Company outcomes, public operating evidence, completed Luna Sol advisory work, and Ryan Miller&apos;s prior employment are labeled separately. Third-party marks belong to their respective owners and do not imply endorsement.</p></section><section><h2>Acceptable use</h2><p>Do not misuse the site, interfere with its operation, attempt unauthorized access, submit unlawful material, or represent site content as a guaranteed result. Do not rely on the site for emergency or safety-critical decisions.</p></section><section><h2>Availability and changes</h2><p>The site and its tools may change or become unavailable. Luna Sol may update these terms as the service evolves. Continued use after an update means the revised terms govern that use to the extent permitted by law.</p></section></article></main><SiteFooter /></>;
}
