CREATE TABLE `market_stream_priority_current` (
	`stream_id` text PRIMARY KEY NOT NULL,
	`connection_epoch` integer NOT NULL,
	`head_sequence` integer NOT NULL,
	`head_state` text NOT NULL,
	`head_execution_eligible` integer NOT NULL,
	`head_processed_at` integer NOT NULL,
	`head_available_at` integer NOT NULL,
	`live_proof_sequence` integer,
	`quote_sequence` integer,
	`quote_session_date` text,
	`quote_provider_time` integer,
	`quote_received_at` integer,
	`quote_processed_at` integer,
	`quote_available_at` integer,
	`quote_price` real,
	`quote_size` integer,
	`live_proof_hash` text,
	`quote_hash` text,
	`projection_hash` text NOT NULL,
	`payload_json` text NOT NULL,
	`updated_at` integer NOT NULL,
	CONSTRAINT "market_stream_priority_epoch_check" CHECK("market_stream_priority_current"."connection_epoch" >= 0),
	CONSTRAINT "market_stream_priority_head_sequence_check" CHECK("market_stream_priority_current"."head_sequence" > 0),
	CONSTRAINT "market_stream_priority_head_state_check" CHECK("market_stream_priority_current"."head_state" IN ('DISCONNECTED','CONNECTING','AUTHENTICATING','SUBSCRIBING','LIVE','SILENT','BACKOFF','DEGRADED')),
	CONSTRAINT "market_stream_priority_execution_eligible_check" CHECK("market_stream_priority_current"."head_execution_eligible" IN (0,1)),
	CONSTRAINT "market_stream_priority_quote_shape_check" CHECK(("market_stream_priority_current"."quote_sequence" IS NULL AND "market_stream_priority_current"."live_proof_sequence" IS NULL AND "market_stream_priority_current"."quote_session_date" IS NULL AND "market_stream_priority_current"."quote_provider_time" IS NULL AND "market_stream_priority_current"."quote_received_at" IS NULL AND "market_stream_priority_current"."quote_processed_at" IS NULL AND "market_stream_priority_current"."quote_available_at" IS NULL AND "market_stream_priority_current"."quote_price" IS NULL AND "market_stream_priority_current"."quote_size" IS NULL AND "market_stream_priority_current"."live_proof_hash" IS NULL AND "market_stream_priority_current"."quote_hash" IS NULL) OR ("market_stream_priority_current"."head_state" = 'LIVE' AND "market_stream_priority_current"."quote_sequence" = "market_stream_priority_current"."head_sequence" AND "market_stream_priority_current"."live_proof_sequence" > 0 AND "market_stream_priority_current"."live_proof_sequence" < "market_stream_priority_current"."quote_sequence" AND "market_stream_priority_current"."quote_session_date" IS NOT NULL AND "market_stream_priority_current"."quote_provider_time" >= 0 AND "market_stream_priority_current"."quote_received_at" >= 0 AND "market_stream_priority_current"."quote_processed_at" >= 0 AND "market_stream_priority_current"."quote_available_at" >= 0 AND "market_stream_priority_current"."quote_price" > 0 AND "market_stream_priority_current"."quote_size" >= 0 AND "market_stream_priority_current"."live_proof_hash" IS NOT NULL AND "market_stream_priority_current"."quote_hash" IS NOT NULL))
);
