import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const pageUrl = new URL("../app/page.tsx", import.meta.url);
const componentUrl = new URL("../app/components/MooDecisionSurface.tsx", import.meta.url);

test("Strict MOO uses the served forecast block and an exact prior session", async () => {
  const page = await readFile(pageUrl, "utf8");
  assert.match(page, /strictResearchForecast = selectedStrictForecast;/);
  assert.doesNotMatch(page, /strictResearchForecast = selectedStrictForecast\?\.researchForecast/);
  assert.doesNotMatch(page, /latestStrictCapture|selectedStrictForecast\?\.snapshots/);
  assert.match(page, /Research estimates below[\s\S]+never populate this snapshot/);
  assert.match(page, /mooSystemStatus\.decisionSnapshot/);
  assert.match(page, /previousTargetSession\(strictTargetSession\)/);
  assert.equal([...page.matchAll(/previousTargetSession\(strictTargetSession\)/g)].length, 1);
  assert.match(page, /=== mooPlanningPreviousSession/);
  assert.match(page, /const mooPlanningInput = \{/);
  assert.match(page, /planning=\{mooPlanningInput\}/);
  assert.match(page, /transport=\{mooSystemStatus\?\.transport\}/);
  assert.doesNotMatch(page, /planningSources\.planningInput = \{/);
  assert.match(page, /let timedOut = false/);
  assert.match(page, /timedOut = true; controller\.abort\(\)/);
  assert.match(page, /forecastEnvelope\?\.targetDate === mooTargetDate/);
  assert.match(page, /type MooSessionSelection = \{/);
  assert.match(page, /mode: "FOLLOW_ACTIVE" \| "AUDIT_PINNED"/);
  assert.match(page, /selection\.mode === "AUDIT_PINNED" && selection\.date/);
  assert.match(page, /reconcileMooSessionSelection\(current, clockMs\)/);
  assert.match(page, /setMooSessionSelection\(\{ date: event\.target\.value, mode: "AUDIT_PINNED" \}\)/);
  assert.match(page, /Return to active session/);
  assert.match(page, /Determining active session/);
  assert.doesNotMatch(page, /defaultTargetSession\(clockMs \?\? lastRefreshAt \?\? 0\)/);
  assert.match(page, /Volver a la sesión activa/);
  assert.match(page, /FOLLOWING ACTIVE SESSION · AUTOMATIC ROLLOVER ON/);
  assert.match(page, /AUDIT DATE PINNED · AUTOMATIC ROLLOVER PAUSED/);
  assert.match(page, /PINNED AUDIT/);
  assert.match(page, /AUDITORÍA FIJADA/);
  assert.match(page, /strictForecastPollRef\.current = \{ sequence: strictForecastPollRef\.current\.sequence \+ 1, controller: null, targetDate: null \}/);
  assert.match(page, /strictMarketPollRef\.current = \{ sequence: strictMarketPollRef\.current\.sequence \+ 1, controller: null, targetDate: null \}/);
  assert.match(page, /mooSystemStatusPollRef\.current = \{ sequence: mooSystemStatusPollRef\.current\.sequence \+ 1, controller: null, targetDate: null \}/);
  assert.match(page, /setStrictForecast\(null\)/);
  assert.match(page, /setStrictMarket\(null\)/);
  assert.match(page, /setMooSystemStatus\(null\)/);
  assert.match(page, /enumerateNearbyTargetSessions\(clockMs, \{ past: 5, future: 10 \}\)/);
  assert.match(page, /function StrictStatusUnavailableNotice/);
  assert.match(page, /Current server status is not yet available/);
  assert.equal([...page.matchAll(/<StrictStatusUnavailableNotice lang=\{lang\} message=\{mooSystemStatusError\} \/>/g)].length, 2);
});

test("paper planner consumes the flat public-safe broker status contract", async () => {
  const component = await readFile(componentUrl, "utf8");
  assert.match(component, /effectiveBrokerStatus\?\.configured/);
  assert.match(component, /summarizeMooReadiness\(snapshot, effectiveBrokerStatus\)/);
  assert.match(component, /brokerReadiness\.broker\.indicativeShortable/);
  assert.match(component, /effectiveBrokerStatus\.borrowStatus/);
  assert.doesNotMatch(component, /brokerStatus\?*\.account/);
  assert.doesNotMatch(component, /brokerStatus\?*\.nvda/);
  const readiness = await readFile(new URL("../app/moo-readiness.ts", import.meta.url), "utf8");
  assert.match(readiness, /locateGuaranteed === true/);
  assert.match(readiness, /snapshot\.decision === "SHORT_FAVORED"/);
  assert.match(component, /Preview only[^\n]+never submits an order/);
  assert.match(component, /PAPER_PROFILE_STORAGE_KEY = "aperture-moo-paper-risk-profile:v3"/);
  assert.match(component, /stopOffset: "1\.00"/);
  assert.match(component, /riskBudget: "10\.00"/);
  assert.match(component, /slippageAllowance: "0\.10"/);
  assert.match(component, /maxShares: "1"/);
  assert.match(component, /timeStop: "10:00 ET"/);
  assert.match(component, /window\.localStorage\.getItem\(PAPER_PROFILE_STORAGE_KEY\)/);
  assert.match(component, /window\.localStorage\.setItem\(PAPER_PROFILE_STORAGE_KEY/);
  assert.match(component, /StrictMooJourney/);
  assert.match(component, /strict-audit-details/);
  assert.match(component, /Missing: prior close/);
  assert.match(component, /Missing: premarket current/);
  assert.match(component, /Incomplete high\/low/);
});
