import type { Metadata } from "next";
import { SiteFooter } from "@/app/components/SiteFooter";
import { SiteHeader } from "@/app/components/SiteHeader";

export const metadata: Metadata = { title: "Privacy", description: "Privacy information for the Luna Sol Group website.", alternates: { canonical: "/privacy" } };

export default function PrivacyPage() {
  const contactEmail = process.env.NEXT_PUBLIC_CONTACT_EMAIL || "Rmiller62785@gmail.com";
  return <><SiteHeader /><main id="main" className="trust-page"><header><div className="shell"><span>Trust center</span><h1>Privacy</h1><p>How this website handles information visitors choose to provide.</p></div></header><article className="shell trust-article"><p className="trust-note"><strong>Effective August 12, 2026.</strong> This notice describes the public Luna Sol Group website. It is not a substitute for engagement-specific confidentiality or data-processing terms.</p><section><h2>Information you provide</h2><p>The confidential inquiry form may collect your name, work email, company, and the operating problem you choose to describe. Do not submit credentials, regulated personal data, trade secrets, or information you are not authorized to share.</p></section><section><h2>How inquiry information is used</h2><p>Inquiry information is used to evaluate and respond to your request. The site may route that information to Luna Sol&apos;s private operations workspace and, when configured, to an email delivery provider. An email fallback may be offered if form delivery is unavailable.</p></section><section><h2>Website measurement</h2><p>The site may use privacy-oriented aggregate analytics when configured. Product telemetry is limited to selected interaction events and is designed not to capture names, email addresses, company names, free-form messages, or full URLs. Browser do-not-track signals disable the product event helper.</p></section><section><h2>Device-local tool data</h2><p>Operations Lab tools are designed to compute in the browser unless a tool page clearly states otherwise. Visitors should review the model boundary on each tool before entering information.</p></section><section><h2>Third-party links</h2><p>The site links to company websites, LinkedIn, news sources, and other public resources. Their privacy practices are governed by their own notices.</p></section><section><h2>Retention, access, and questions</h2><p>Luna Sol retains inquiry and operational records only as needed for legitimate business purposes and applicable obligations. To ask about information you submitted, request correction or deletion where applicable, or raise a privacy concern, email <a href={`mailto:${contactEmail}`}>{contactEmail}</a>.</p></section></article></main><SiteFooter /></>;
}
