import { env } from "cloudflare:workers";

type Weight={key:string;label:string;category:string;enabled:number;directionWeight:number;rangeWeight:number;updatedAt:number};
type EventRow={id:string;source:string;category:string;headline:string;summary:string;url:string;eventTime:number;severity:number};
const defaults=[
 {key:"geopolitical",label:"Geopolitical escalation",category:"News risk",directionWeight:0,rangeWeight:.35},
 {key:"news_intensity",label:"Breaking-news intensity",category:"News risk",directionWeight:0,rangeWeight:.15},
 {key:"nvda_earnings",label:"NVDA earnings proximity",category:"Scheduled",directionWeight:0,rangeWeight:.5},
 {key:"macro_release",label:"Major U.S. macro release",category:"Scheduled",directionWeight:0,rangeWeight:.3},
 {key:"sec_filing",label:"New NVDA SEC filing",category:"Company",directionWeight:0,rangeWeight:.2},
 {key:"monday",label:"Monday effect (experimental)",category:"Calendar",directionWeight:0,rangeWeight:0},
 {key:"pay_period",label:"Pay-period proximity (experimental)",category:"Calendar",directionWeight:0,rangeWeight:0},
];
const schema=[
 `CREATE TABLE IF NOT EXISTS forecast_weights (key TEXT PRIMARY KEY NOT NULL,label TEXT NOT NULL,category TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 1,direction_weight REAL NOT NULL DEFAULT 0,range_weight REAL NOT NULL DEFAULT 0,updated_at INTEGER NOT NULL)`,
 `CREATE TABLE IF NOT EXISTS market_events (id TEXT PRIMARY KEY NOT NULL,source TEXT NOT NULL,category TEXT NOT NULL,headline TEXT NOT NULL,summary TEXT NOT NULL,url TEXT NOT NULL,event_time INTEGER NOT NULL,severity REAL NOT NULL,created_at INTEGER NOT NULL)`,
 `CREATE INDEX IF NOT EXISTS market_events_time_idx ON market_events (event_time DESC)`,
 `CREATE TABLE IF NOT EXISTS forecast_snapshots (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,target_date TEXT NOT NULL,captured_at INTEGER NOT NULL,interval_label TEXT NOT NULL,base_median REAL NOT NULL,adjusted_median REAL NOT NULL,adjusted_low REAL NOT NULL,adjusted_high REAL NOT NULL,factors_json TEXT NOT NULL,actual_open REAL,median_error REAL)`,
 `CREATE UNIQUE INDEX IF NOT EXISTS forecast_snapshots_target_interval_idx ON forecast_snapshots (target_date,interval_label)`,
];
let eventCache:{expires:number;rows:EventRow[]}|null=null;
const json=(body:unknown,status=200)=>Response.json(body,{status,headers:{"Cache-Control":"no-store, no-cache, must-revalidate"}});
function db(){if(!env.DB)throw new Error("Forecast database is unavailable");return env.DB}
async function ensure(){const d=db(),now=Date.now();await d.batch(schema.map(x=>d.prepare(x)));await d.batch(defaults.map(x=>d.prepare(`INSERT OR IGNORE INTO forecast_weights (key,label,category,enabled,direction_weight,range_weight,updated_at) VALUES (?,?,?,1,?,?,?)`).bind(x.key,x.label,x.category,x.directionWeight,x.rangeWeight,now)))}
const clean=(v:unknown)=>typeof v==="string"?v.replace(/\s+/g," ").trim():"";
function classify(headline:string,summary:string){const text=`${headline} ${summary}`.toLowerCase();if(/iran|missile|airstrike|air strike|war|hormuz|blockade|military strike|invasion|retaliat/.test(text))return{category:"Geopolitical",severity:3};if(/earnings|quarterly results|guidance|revenue forecast/.test(text))return{category:"Earnings",severity:2.5};if(/fomc|federal reserve|interest rate|inflation|cpi|ppi|payroll|employment report|jobs report/.test(text))return{category:"Macro",severity:2.5};if(/nvidia|nvda|semiconductor|chip export|ai chip/.test(text))return{category:"NVDA / Semis",severity:2};return{category:"Market",severity:1}}
async function pullEvents(){if(eventCache&&eventCache.expires>Date.now())return eventCache.rows;const key=(globalThis as unknown as {process?:{env?:Record<string,string>}}).process?.env?.FINNHUB_API_KEY,now=Math.floor(Date.now()/1000),from=new Date(Date.now()-3*864e5).toISOString().slice(0,10),to=new Date(Date.now()+45*864e5).toISOString().slice(0,10),rows:EventRow[]=[];
 if(key){const h={"X-Finnhub-Token":key,Accept:"application/json"};const[general,company,earnings]=await Promise.allSettled([fetch("https://finnhub.io/api/v1/news?category=general&minId=0",{headers:h,cache:"no-store"}).then(r=>r.ok?r.json():[]),fetch(`https://finnhub.io/api/v1/company-news?symbol=NVDA&from=${from}&to=${new Date().toISOString().slice(0,10)}`,{headers:h,cache:"no-store"}).then(r=>r.ok?r.json():[]),fetch(`https://finnhub.io/api/v1/calendar/earnings?from=${from}&to=${to}&symbol=NVDA`,{headers:h,cache:"no-store"}).then(r=>r.ok?r.json():{})]);for(const result of[general,company])if(result.status==="fulfilled"&&Array.isArray(result.value))for(const item of result.value.slice(0,80) as Array<Record<string,unknown>>){const headline=clean(item.headline),summary=clean(item.summary),c=classify(headline,summary),time=Number(item.datetime)||now;if(!headline||time<now-3*86400)continue;if(c.severity<2&&!/nvidia|nvda|semiconductor|nasdaq|oil|iran|war|fed|inflation/i.test(`${headline} ${summary}`))continue;rows.push({id:`fh-${item.id??time}-${headline.slice(0,20)}`,source:clean(item.source)||"Finnhub",category:c.category,headline,summary,url:clean(item.url),eventTime:time*1000,severity:c.severity})}if(earnings.status==="fulfilled"){const list=(earnings.value as {earningsCalendar?:Array<Record<string,unknown>>}).earningsCalendar??[];for(const e of list)rows.push({id:`earn-${e.date}-${e.symbol}`,source:"Finnhub earnings calendar",category:"Earnings",headline:`${e.symbol??"NVDA"} earnings scheduled`,summary:`Scheduled ${e.hour??"time not supplied"}; EPS estimate ${e.epsEstimate??"—"}.`,url:"",eventTime:Date.parse(`${e.date}T12:00:00Z`),severity:3})}}
 try{const sec=await fetch("https://data.sec.gov/submissions/CIK0001045810.json",{headers:{"User-Agent":"NVDA Opening Intelligence personal research contact@example.com",Accept:"application/json"},cache:"no-store"});if(sec.ok){const j=await sec.json() as {filings?:{recent?:Record<string,string[]>}},r=j.filings?.recent;if(r){for(let i=0;i<Math.min(20,r.form?.length??0);i++){const filed=r.filingDate?.[i],form=r.form?.[i],accession=r.accessionNumber?.[i];if(!filed||!form||!accession||Date.parse(filed)<Date.now()-7*864e5||!/^(8-K|10-Q|10-K|4)$/.test(form))continue;rows.push({id:`sec-${accession}`,source:"SEC EDGAR",category:"SEC filing",headline:`NVIDIA filed Form ${form}`,summary:`Official filing disseminated ${filed}.`,url:`https://www.sec.gov/Archives/edgar/data/1045810/${accession.replace(/-/g,"")}/`,eventTime:Date.parse(`${filed}T12:00:00Z`),severity:form==="8-K"?2.5:2})}}}}catch{}
 try{const bls=await fetch("https://www.bls.gov/schedule/news_release/bls.ics",{headers:{"User-Agent":"NVDA Opening Intelligence personal research contact@example.com"},cache:"no-store"});if(bls.ok){const ics=await bls.text();for(const block of ics.split("BEGIN:VEVENT").slice(1)){const raw=block.match(/DTSTART[^:]*:(\d{8})T?(\d{4})?/),summary=clean(block.match(/SUMMARY:(.+)/)?.[1]);if(!raw||!summary||!/consumer price|producer price|employment situation|job openings|productivity/i.test(summary))continue;const d=raw[1],time=raw[2]??"0830",stamp=Date.parse(`${d.slice(0,4)}-${d.slice(4,6)}-${d.slice(6,8)}T${time.slice(0,2)}:${time.slice(2)}:00-04:00`);if(stamp<Date.now()-864e5||stamp>Date.now()+45*864e5)continue;rows.push({id:`bls-${d}-${summary}`,source:"U.S. Bureau of Labor Statistics",category:"Macro",headline:summary,summary:"Official scheduled U.S. economic release.",url:"https://www.bls.gov/schedule/",eventTime:stamp,severity:3})}}}catch{}
 const dedup=[...new Map(rows.sort((a,b)=>b.eventTime-a.eventTime).map(x=>[x.id,x])).values()].slice(0,100);eventCache={expires:Date.now()+300_000,rows:dedup};return dedup}
function signals(events:EventRow[],targetDate:string){const recent=events.filter(e=>e.eventTime>Date.now()-72*3600_000),target=events.filter(e=>new Date(e.eventTime).toISOString().slice(0,10)===targetDate),day=Number(targetDate.slice(-2)),weekday=new Date(`${targetDate}T12:00:00Z`).getUTCDay();return{geopolitical:Math.min(1,recent.filter(e=>e.category==="Geopolitical").reduce((m,e)=>Math.max(m,e.severity/3),0)),news_intensity:Math.min(1,recent.length/12),nvda_earnings:target.some(e=>e.category==="Earnings")?1:0,macro_release:target.some(e=>e.category==="Macro")?1:0,sec_filing:recent.some(e=>e.category==="SEC filing")?1:0,monday:weekday===1?1:0,pay_period:day<=3||Math.abs(day-15)<=2?1:0}}
async function weights(){const r=await db().prepare(`SELECT key,label,category,enabled,direction_weight AS directionWeight,range_weight AS rangeWeight,updated_at AS updatedAt FROM forecast_weights ORDER BY category,label`).all();return r.results as unknown as Weight[]}
export async function GET(request:Request){try{await ensure();const u=new URL(request.url),targetDate=u.searchParams.get("targetDate")??new Date().toISOString().slice(0,10),events=await pullEvents(),d=db(),now=Date.now();if(events.length)await d.batch(events.slice(0,50).map(e=>d.prepare(`INSERT INTO market_events (id,source,category,headline,summary,url,event_time,severity,created_at) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET headline=excluded.headline,summary=excluded.summary,event_time=excluded.event_time,severity=excluded.severity`).bind(e.id,e.source,e.category,e.headline,e.summary,e.url,e.eventTime,e.severity,now)));const w=await weights(),s=signals(events,targetDate),contributions=w.map(x=>({key:x.key,label:x.label,category:x.category,enabled:Boolean(x.enabled),signal:s[x.key as keyof typeof s]??0,directionBps:Boolean(x.enabled)?(s[x.key as keyof typeof s]??0)*x.directionWeight:0,rangePct:Boolean(x.enabled)?(s[x.key as keyof typeof s]??0)*x.rangeWeight:0})),snap=await d.prepare(`SELECT id,target_date AS targetDate,captured_at AS capturedAt,interval_label AS intervalLabel,base_median AS baseMedian,adjusted_median AS adjustedMedian,adjusted_low AS adjustedLow,adjusted_high AS adjustedHigh,actual_open AS actualOpen,median_error AS medianError FROM forecast_snapshots ORDER BY captured_at DESC LIMIT 100`).all();return json({weights:w,events:events.slice(0,40),contributions,adjustment:{directionBps:contributions.reduce((a,x)=>a+x.directionBps,0),rangeMultiplier:Math.max(.5,1+contributions.reduce((a,x)=>a+x.rangePct,0))},snapshots:snap.results})}catch(e){return json({error:e instanceof Error?e.message:"Forecast intelligence unavailable"},503)}}
export async function PUT(request:Request){try{await ensure();const b=await request.json() as {weights?:Array<Partial<Weight>>};if(!Array.isArray(b.weights))return json({error:"weights array required"},400);const d=db(),now=Date.now();await d.batch(b.weights.filter(x=>typeof x.key==="string").map(x=>d.prepare(`UPDATE forecast_weights SET enabled=?,direction_weight=?,range_weight=?,updated_at=? WHERE key=?`).bind(x.enabled?1:0,Math.max(-100,Math.min(100,Number(x.directionWeight)||0)),Math.max(-.75,Math.min(2,Number(x.rangeWeight)||0)),now,x.key)));return json({weights:await weights()})}catch(e){return json({error:e instanceof Error?e.message:"Unable to update weights"},503)}}
export async function POST(request:Request){try{await ensure();const b=await request.json() as Record<string,unknown>,nums=["baseMedian","adjustedMedian","adjustedLow","adjustedHigh"] as const;if(typeof b.targetDate!=="string"||typeof b.intervalLabel!=="string"||nums.some(k=>typeof b[k]!=="number"||!Number.isFinite(b[k])))return json({error:"Valid snapshot values required"},400);const actual=typeof b.actualOpen==="number"&&Number.isFinite(b.actualOpen)?b.actualOpen:null,error=actual==null?null:Math.abs(actual-(b.adjustedMedian as number)),d=db();await d.prepare(`INSERT INTO forecast_snapshots (target_date,captured_at,interval_label,base_median,adjusted_median,adjusted_low,adjusted_high,factors_json,actual_open,median_error) VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(target_date,interval_label) DO UPDATE SET captured_at=excluded.captured_at,base_median=excluded.base_median,adjusted_median=excluded.adjusted_median,adjusted_low=excluded.adjusted_low,adjusted_high=excluded.adjusted_high,factors_json=excluded.factors_json,actual_open=COALESCE(excluded.actual_open,actual_open),median_error=COALESCE(excluded.median_error,median_error)`).bind(b.targetDate,Date.now(),b.intervalLabel,b.baseMedian,b.adjustedMedian,b.adjustedLow,b.adjustedHigh,JSON.stringify(b.factors??[]),actual,error).run();if(actual!=null)await d.prepare(`UPDATE forecast_snapshots SET actual_open=?,median_error=ABS(?-adjusted_median) WHERE target_date=?`).bind(actual,actual,b.targetDate).run();return json({ok:true})}catch(e){return json({error:e instanceof Error?e.message:"Unable to save snapshot"},503)}}
