"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";

type Bar = { time: number; open: number; high: number; low: number; close: number; volume: number };
type Daily = { date: string; high: number; low: number; close: number };
type Payload = { symbol: "NVDA"; price: number | null; previousClose: number | null; asOf: string; session: string; source: string; realtime: boolean; bars: Bar[]; daily: Daily[]; day: { open: number|null; high:number|null; low:number|null; volume:number }; premarket:{high:number|null;low:number|null;volume:number}; firstMinute:{close:number|null;volume:number} };

const money = (v:number|null|undefined) => Number.isFinite(v) ? `$${v!.toFixed(2)}` : "—";
const compact = new Intl.NumberFormat("en-US",{notation:"compact",maximumFractionDigits:1});
function ema(values:number[], period:number){ if(!values.length)return[]; const k=2/(period+1); const out=[values[0]]; for(let i=1;i<values.length;i++)out.push(values[i]*k+out[i-1]*(1-k)); return out; }

function median(values:number[]){const s=values.filter(Number.isFinite).sort((a,b)=>a-b);if(!s.length)return 0;const m=Math.floor(s.length/2);return s.length%2?s[m]:(s[m-1]+s[m])/2}
function classifyCandle(c:Bar,prev:Bar|undefined,history:Bar[]){const range=Math.max(.0001,c.high-c.low),body=Math.abs(c.close-c.open),upper=c.high-Math.max(c.open,c.close),lower=Math.min(c.open,c.close)-c.low,ratio=body/range,bull=c.close>=c.open;const prior=history.length>=4?history.at(-1)!.close-history[0].close:0;const engulf=prev&&bull!==(prev.close>=prev.open)&&body>=Math.abs(prev.close-prev.open)*1.05&&Math.min(c.open,c.close)<=Math.min(prev.open,prev.close)&&Math.max(c.open,c.close)>=Math.max(prev.open,prev.close);if(engulf&&((bull&&prior<0)||(!bull&&prior>0)))return{type:bull?"Bullish engulfing":"Bearish engulfing",copy:"The body spans the prior opposite body after a short move. This is reversal-shaped evidence, not proof of a reversal."};if(ratio<=.08)return{type:"Long-legged doji",copy:"Open and close are nearly equal relative to the full range. Both sides pushed price, but neither held control into the current close."};if(ratio>=.1&&lower>=body*2.1&&upper<=body*.8&&prior<0)return{type:"Hammer-shaped rejection",copy:"Price traded lower after a short decline and recovered toward the body. Confirmation requires later price action."};if(ratio>=.1&&upper>=body*2.1&&lower<=body*.8&&prior>0)return{type:"Shooting-star rejection",copy:"Price traded higher after a short rise and returned toward the body. This shows rejection, not a guaranteed reversal."};if(ratio>=.88&&upper/range<=.06&&lower/range<=.06)return{type:bull?"Bullish marubozu":"Bearish marubozu",copy:"Most of the range is directional body with very small wicks. It describes strong control during this minute only."};if(ratio<.3)return{type:"Spinning top",copy:"A small body sits inside a wider range. The minute rotated in both directions and closed without clean control."};return{type:bull?"Bullish body candle":"Bearish body candle",copy:`This candle is ${bull?"above":"below"} its open. Its location, volume and follow-through matter more than the name.`}}
function candleRead(bars:Bar[]){if(!bars.length)return null;const c=bars.at(-1)!,prev=bars.at(-2),hist=bars.slice(-7,-2),pattern=classifyCandle(c,prev,hist);const range=Math.max(.01,c.high-c.low),body=Math.abs(c.close-c.open),bps=(c.close/c.open-1)*10000,bodyRatio=body/range,priorRanges=bars.slice(-21,-1).map(x=>(x.high-x.low)/x.open*10000),typical=Math.max(.1,median(priorRanges)),relative=Math.abs(bps)/typical,priorVolumes=bars.slice(-21,-1).map(x=>x.volume).filter(x=>x>0),avgVol=priorVolumes.reduce((a,b)=>a+b,0)/Math.max(1,priorVolumes.length),volumePace=avgVol?c.volume/avgVol:0;const recent5=bars.slice(-6,-1),recent15=bars.slice(-16,-1);const trend=(rows:Bar[])=>{if(rows.length<3)return"building";const change=rows.at(-1)!.close-rows[0].open,hh=rows.slice(1).filter((x,i)=>x.high>rows[i].high).length,hl=rows.slice(1).filter((x,i)=>x.low>rows[i].low).length,lh=rows.slice(1).filter((x,i)=>x.high<rows[i].high).length,ll=rows.slice(1).filter((x,i)=>x.low<rows[i].low).length;return change>0&&hh+hl>=lh+ll?"rising":change<0&&lh+ll>=hh+hl?"falling":"sideways"};const higherLow=prev?c.low>prev.low:false,lowerHigh=prev?c.high<prev.high:false;return{c,prev,pattern,bps,bodyRatio,relative,typical,volumePace,trend5:trend(recent5),trend15:trend(recent15),higherLow,lowerHigh,direction:bps>.75?"up":bps<-.75?"down":"flat",wick:upperLower(c),recent:bars.slice(-9)}}
function upperLower(c:Bar){const body=Math.abs(c.close-c.open),u=c.high-Math.max(c.open,c.close),l=Math.min(c.open,c.close)-c.low;return u>Math.max(body,l)*1.5?"upper rejection":l>Math.max(body,u)*1.5?"lower rejection":"balanced wicks"}

function SessionChart({bars,ema9,ema21}:{bars:Bar[];ema9:number[];ema21:number[]}){
  const canvas=useRef<HTMLCanvasElement>(null);
  useEffect(()=>{ const el=canvas.current;if(!el||bars.length<2)return; const rect=el.getBoundingClientRect(),dpr=window.devicePixelRatio||1;el.width=rect.width*dpr;el.height=rect.height*dpr;const c=el.getContext("2d");if(!c)return;c.scale(dpr,dpr);const w=rect.width,h=rect.height,p={l:12,r:58,t:15,b:24};const vals=[...bars.map(b=>b.close),...ema9,...ema21];const min=Math.min(...vals),max=Math.max(...vals),span=Math.max(max-min,.01);const x=(i:number)=>p.l+i*(w-p.l-p.r)/(bars.length-1);const y=(v:number)=>p.t+(max-v)*(h-p.t-p.b)/span;c.clearRect(0,0,w,h);c.strokeStyle="rgba(118,151,176,.14)";c.lineWidth=1;for(let i=0;i<5;i++){const yy=p.t+i*(h-p.t-p.b)/4;c.beginPath();c.moveTo(p.l,yy);c.lineTo(w-p.r,yy);c.stroke();c.fillStyle="#8ea5b7";c.font="10px system-ui";c.fillText((max-i*span/4).toFixed(2),w-p.r+8,yy+3)}const line=(arr:number[],color:string,width:number)=>{c.beginPath();arr.forEach((v,i)=>i?c.lineTo(x(i),y(v)):c.moveTo(x(i),y(v)));c.strokeStyle=color;c.lineWidth=width;c.stroke()};line(bars.map(b=>b.close),"#f4f8fb",1.4);line(ema21,"#a98cff",1.7);line(ema9,"#f5c75b",2);const last=bars.at(-1)!;c.fillStyle="#f5c75b";c.beginPath();c.arc(x(bars.length-1),y(last.close),4,0,Math.PI*2);c.fill();},[bars,ema9,ema21]);
  return <canvas ref={canvas} aria-label="NVDA full-session price chart with EMA 9 and EMA 21"/>;
}

export default function Home(){
 const [data,setData]=useState<Payload|null>(null),[error,setError]=useState(""),[ticks,setTicks]=useState(0);const [days,setDays]=useState<3|4>(4);
 const refresh=useCallback(async()=>{try{const r=await fetch(`/api/market?symbol=NVDA&t=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw new Error();setData(await r.json());setError("");setTicks(x=>x+1)}catch{setError("Feed retrying automatically")}},[]);
 useEffect(()=>{refresh();const id=window.setInterval(refresh,1000);return()=>clearInterval(id)},[refresh]);
 const analysis=useMemo(()=>{if(!data?.daily.length)return null;const d=data.daily.slice(-days),closes=data.bars.map(b=>b.close),e9=ema(closes,9),e21=ema(closes,21),last=closes.at(-1)??data.price??0,prev=closes.at(-2)??last;const high=Math.max(...d.map(x=>x.high)),low=Math.min(...d.map(x=>x.low)),close=d.at(-1)!.close,block=(high+low+close)/3,weights=d.map((_,i)=>i+1),weighted=d.reduce((s,b,i)=>s+((b.high+b.low+b.close)/3)*weights[i],0)/weights.reduce((a,b)=>a+b,0),lo=low+(high-low)/3,hi=low+2*(high-low)/3;const fast=e9.at(-1)??last,slow=e21.at(-1)??last,fastPrev=e9.at(-4)??fast;const bullish=last>fast&&fast>slow&&fast>fastPrev,bearish=last<fast&&fast<slow&&fast<fastPrev;const regime=bullish?"BUYERS IN CONTROL":bearish?"SELLERS IN CONTROL":"MIXED / ROTATING";const tone=bullish?"up":bearish?"down":"flat";const zone=last>hi?"UPPER THIRD":last<lo?"LOWER THIRD":"MIDDLE THIRD";const candle=candleRead(data.bars);const priorHigh=d.at(-2)?.high??null,open=data.day.open,gap=open!=null&&data.previousClose!=null?open-data.previousClose:null,aboveOpen=open!=null?last>open:false,nearPriorHigh=priorHigh!=null?Math.abs(last-priorHigh)<=Math.max(.15,last*.0015):false;return{d,e9,e21,last,change:last-(data.previousClose??last),changePct:(last/(data.previousClose??last)-1)*100,high,low,block,weighted,lo,hi,fast,slow,spread:fast-slow,slope:fast-fastPrev,regime,tone,zone,minuteMove:last-prev,candle,priorHigh,gap,aboveOpen,nearPriorHigh}},[data,days]);
 return <main className="app-shell">
  <header className="topbar"><div className="brand-block"><div className="brand-mark">N</div><div><div className="eyebrow">PAPI ROBERTO MARKET INTELLIGENCE</div><h1>Nvidia <span>Live Structure</span></h1></div></div><div className="top-status"><div className={`status-chip ${data?.realtime?"ok":""}`}><i className="status-dot"/><strong>{data?.realtime?"SIP REAL-TIME":"PUBLIC FEED"}</strong></div><div className="status-chip"><strong>1 SEC</strong> refresh</div><div className="status-chip"><strong>{data?.session??"—"}</strong></div></div></header>
  {error&&<div className="feed-alert">{error}</div>}
  <section className="market-grid">
   <article className="panel market-card"><div className="panel-kicker">Live reference price</div><div className="market-price">{money(analysis?.last)}</div><div className={`market-change ${analysis?.change&&analysis.change>0?"up":analysis?.change&&analysis.change<0?"down":""}`}>{analysis?`${analysis.change>=0?"+":""}${analysis.change.toFixed(2)} · ${analysis.changePct>=0?"+":""}${analysis.changePct.toFixed(2)}% vs prior close`:"Connecting…"}</div><div className="quote-row"><span>Open</span><strong>{money(data?.day.open)}</strong><span>High</span><strong>{money(data?.day.high)}</strong><span>Low</span><strong>{money(data?.day.low)}</strong><span>Volume</span><strong>{data?compact.format(data.day.volume):"—"}</strong></div><div className="market-meta">{data?.source??"Connecting to NVDA feed…"}<br/>{data?.asOf?`Last observation ${new Date(data.asOf).toLocaleTimeString()}`:""}</div><div className="target-box"><div><span>Structural zone</span><strong>{analysis?.zone??"—"}</strong></div><div><span>EMA regime</span><strong className={analysis?.tone}>{analysis?.regime??"—"}</strong></div></div></article>
   <article className="panel chart-card"><div className="panel-heading"><div><div className="panel-kicker">Today · complete session</div><h2>NVDA price action</h2></div><div className="chart-legend"><span><i className="price-dot"/>Price</span><span><i className="ema9-dot"/>EMA 9</span><span><i className="ema21-dot"/>EMA 21</span></div></div><div className="canvas-wrap">{data?.bars.length?<SessionChart bars={data.bars} ema9={analysis?.e9??[]} ema21={analysis?.e21??[]}/>:<div className="loading">Waiting for session bars…</div>}</div><div className="chart-foot"><span>Premarket through after-hours when available</span><span>{data?.bars.length??0} one-minute bars</span></div></article>
   <article className={`panel ema-card ${analysis?.tone??"flat"}`}><div className="panel-kicker">EMA behavior · descriptive, not forecast</div><div className="ema-status">{analysis?.regime??"CALCULATING"}</div><p className="ema-explain">{analysis?.tone==="up"?"Price is above both averages, EMA 9 is above EMA 21, and the fast average is rising. Buyers currently have the cleaner short-term structure.":analysis?.tone==="down"?"Price is below both averages, EMA 9 is below EMA 21, and the fast average is falling. Sellers currently control the short-term structure.":"The averages and price are not aligned. Momentum is rotating; wait for price and both EMA slopes to agree."}</p><div className="ema-stack"><div><span>EMA 9 · fast</span><strong>{money(analysis?.fast)}</strong><small className={analysis&&analysis.slope>0?"up":"down"}>{analysis?`${analysis.slope>=0?"▲":"▼"} ${Math.abs(analysis.slope).toFixed(3)} slope`:"—"}</small></div><div><span>EMA 21 · trend</span><strong>{money(analysis?.slow)}</strong><small>slower confirmation</small></div><div><span>Fast / slow spread</span><strong>{analysis?`${analysis.spread>=0?"+":""}${analysis.spread.toFixed(3)}`:"—"}</strong><small>{analysis&&Math.abs(analysis.spread)<.08?"compressed":"separated"}</small></div><div><span>Current minute</span><strong>{analysis?`${analysis.minuteMove>=0?"+":""}${analysis.minuteMove.toFixed(2)}`:"—"}</strong><small>vs prior minute</small></div></div></article>
  </section>
  <section className="section-block"><div className="section-heading"><div><div className="panel-kicker">Live candle intelligence</div><h2>Read the candle, then the sequence</h2></div><div className="section-note">Current one-minute bar · descriptive only</div></div><div className="candle-grid">
   <article className={`panel live-candle-card ${analysis?.candle?.direction??"flat"}`}><div className="candle-visual-wrap"><div className="candle-visual" aria-label="Current NVDA one-minute candlestick"><i style={{top:analysis?.candle?`${(analysis.candle.c.high-Math.max(analysis.candle.c.open,analysis.candle.c.close))/(analysis.candle.c.high-analysis.candle.c.low||1)*100}%`:"10%",height:analysis?.candle?`${Math.max(3,Math.abs(analysis.candle.c.close-analysis.candle.c.open)/(analysis.candle.c.high-analysis.candle.c.low||1)*100)}%`:"30%"}}/><b/></div><span>{analysis?.candle?.direction==="up"?"ABOVE OPEN":analysis?.candle?.direction==="down"?"BELOW OPEN":"NEAR OPEN"}</span></div><div className="candle-reading"><div className="panel-kicker">Technical shape · not a forecast</div><h3>{analysis?.candle?.pattern.type??"Waiting for candle"}</h3><p>{analysis?.candle?.pattern.copy??"The first live candle will appear when session data arrives."}</p><div className="candle-callout"><strong>{analysis?.candle?`${analysis.candle.bps>=0?"+":""}${analysis.candle.bps.toFixed(1)} bps from minute open`:"—"}</strong><span>{analysis?.candle?`${analysis.candle.relative.toFixed(1)}× typical one-minute range · ${analysis.candle.wick}`:""}</span></div></div><div className="ohlc"><div><span>Open</span><strong>{money(analysis?.candle?.c.open)}</strong></div><div><span>High</span><strong>{money(analysis?.candle?.c.high)}</strong></div><div><span>Low</span><strong>{money(analysis?.candle?.c.low)}</strong></div><div><span>Close / live</span><strong>{money(analysis?.candle?.c.close)}</strong></div><div><span>Range</span><strong>{money(analysis?.candle?analysis.candle.c.high-analysis.candle.c.low:null)}</strong></div><div><span>Volume pace</span><strong>{analysis?.candle?`${analysis.candle.volumePace.toFixed(1)}×`:"—"}</strong></div></div></article>
   <article className="panel sequence-card"><div className="panel-heading"><div><div className="panel-kicker">Last nine minutes</div><h3>Candle sequence</h3></div><span className="closed-note">Last bar may still be forming</span></div><div className="mini-sequence">{analysis?.candle?.recent.map((b,i,all)=>{const high=Math.max(...all.map(x=>x.high)),low=Math.min(...all.map(x=>x.low)),span=Math.max(.01,high-low),wickTop=(high-b.high)/span*100,wickH=(b.high-b.low)/span*100,bodyTop=(high-Math.max(b.open,b.close))/span*100,bodyH=Math.max(3,Math.abs(b.close-b.open)/span*100);return <div className={`mini ${b.close>b.open?"up":b.close<b.open?"down":"flat"}`} key={b.time}><i style={{top:`${wickTop}%`,height:`${wickH}%`}}/><b style={{top:`${bodyTop}%`,height:`${bodyH}%`}}/><small>{new Date(b.time).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}</small></div>})}</div><div className="sequence-metrics"><div><span>Prior 5 bars</span><strong>{analysis?.candle?.trend5??"—"}</strong></div><div><span>Prior 15 bars</span><strong>{analysis?.candle?.trend15??"—"}</strong></div><div><span>Latest low</span><strong>{analysis?.candle?.higherLow?"Higher low":analysis?.candle?.prev?"Not a higher low":"—"}</strong></div><div><span>Latest high</span><strong>{analysis?.candle?.lowerHigh?"Lower high":analysis?.candle?.prev?"Not a lower high":"—"}</strong></div></div><p className="sequence-copy">A candle is evidence, not an entry by itself. Read the completed shape, its location versus the official open, and whether the next completed candle confirms or rejects it.</p></article>
   <article className="panel opening-card"><div className="panel-kicker">Transcript playbook · live checks</div><h3>Opening structure</h3><div className="check-list"><div className={analysis?.aboveOpen?"positive":"negative"}><i/ ><span>Price vs official open</span><strong>{analysis?.aboveOpen?"ABOVE":"BELOW"} · {money(data?.day.open)}</strong></div><div className={analysis?.gap!=null&&analysis.gap>0?"positive":analysis?.gap!=null&&analysis.gap<0?"negative":"neutral"}><i/><span>Opening gap</span><strong>{analysis?.gap!=null?`${analysis.gap>=0?"+":""}${analysis.gap.toFixed(2)}`:"—"}</strong></div><div className={analysis?.nearPriorHigh?"warning":"neutral"}><i/><span>Yesterday’s high</span><strong>{money(analysis?.priorHigh)} · {analysis?.nearPriorHigh?"NEAR":"CLEAR"}</strong></div><div className={analysis?.candle?.higherLow?"positive":"neutral"}><i/><span>Higher-low confirmation</span><strong>{analysis?.candle?.higherLow?"PRESENT":"NOT PRESENT"}</strong></div><div className={analysis?.candle?.wick==="upper rejection"?"negative":analysis?.candle?.wick==="lower rejection"?"positive":"neutral"}><i/><span>Current rejection</span><strong>{analysis?.candle?.wick?.toUpperCase()??"—"}</strong></div></div><div className="playbook-note"><strong>From the transcript</strong><p>The opening price acts as a reference line. A failed reclaim, a higher low after rejection, and the sequence of completed candles carry more information than guessing the next candle’s color.</p></div></article>
  </div></section>
  <section className="section-block"><div className="section-heading"><div><div className="panel-kicker">Structure before action</div><h2>Pivot and rule-of-thirds map</h2></div><div className="day-switch"><button className={days===3?"active":""} onClick={()=>setDays(3)}>3 sessions</button><button className={days===4?"active":""} onClick={()=>setDays(4)}>4 sessions</button></div></div><div className="structure-grid">
   <article className="panel thirds-card"><div className="third upper"><div><b>UPPER THIRD</b><span>Buyer control / extension</span></div><strong>{money(analysis?.hi)} → {money(analysis?.high)}</strong></div><div className="third middle"><div><b>MIDDLE THIRD</b><span>Rotation / no-trade pressure</span></div><strong>{money(analysis?.lo)} → {money(analysis?.hi)}</strong><i style={{left:analysis?`${Math.max(0,Math.min(100,(analysis.last-analysis.low)/(analysis.high-analysis.low)*100))}%`:"50%"}}/></div><div className="third lower"><div><b>LOWER THIRD</b><span>Weakness / capital protection</span></div><strong>{money(analysis?.low)} → {money(analysis?.lo)}</strong></div></article>
   <article className="panel level-card"><div className="panel-kicker">Decision levels</div><div className="big-level">{money(analysis?Math.min(analysis.block,analysis.weighted):null)}–{money(analysis?Math.max(analysis.block,analysis.weighted):null)}</div><p>Block and recency-weighted pivots. Treat this cluster as an equilibrium area, not an automatic entry.</p><dl><div><dt>Upper-third trigger</dt><dd>{money(analysis?.hi)}</dd></div><div><dt>Lower-third line</dt><dd>{money(analysis?.lo)}</dd></div><div><dt>Range high</dt><dd>{money(analysis?.high)}</dd></div><div><dt>Range low</dt><dd>{money(analysis?.low)}</dd></div></dl></article>
   <article className="panel context-card"><div className="panel-kicker">Opening context</div><h3>Premarket + first minute</h3><dl><div><dt>Premarket high</dt><dd>{money(data?.premarket.high)}</dd></div><div><dt>Premarket low</dt><dd>{money(data?.premarket.low)}</dd></div><div><dt>Premarket volume</dt><dd>{data?compact.format(data.premarket.volume):"—"}</dd></div><div className="highlight"><dt>9:30–9:31 close</dt><dd>{money(data?.firstMinute.close)}</dd></div></dl><p>EMA context stays active for the entire session. The 9:31 observation is a checkpoint, not an end time.</p></article>
  </div></section>
  <section className="section-block"><div className="section-heading"><div><div className="panel-kicker">Exact source data</div><h2>Recent official sessions</h2></div><div className="section-note">No model forecasts · no probability claims</div></div><article className="panel table-panel"><table><thead><tr><th>Date</th><th>High</th><th>Low</th><th>Close</th><th>Daily pivot</th></tr></thead><tbody>{analysis?.d.map(d=><tr key={d.date}><td>{d.date}</td><td>{money(d.high)}</td><td>{money(d.low)}</td><td>{money(d.close)}</td><td>{money((d.high+d.low+d.close)/3)}</td></tr>)}</tbody></table></article></section>
  <footer><strong>NVDA ONLY</strong> · Educational market-structure display, not investment advice. A one-second screen refresh does not guarantee a one-second exchange feed. Verify prices and order details with your broker.<p>{ticks.toLocaleString()} successful refreshes this session.</p></footer>
 </main>
}
