type Quote={high?:Array<number|null>;low?:Array<number|null>;open?:Array<number|null>;close?:Array<number|null>;volume?:Array<number|null>};
type Chart={meta?:{regularMarketPrice?:number;previousClose?:number;chartPreviousClose?:number;marketState?:string};timestamp?:number[];indicators?:{quote?:Quote[]}};
const headers={"User-Agent":"Mozilla/5.0 NVDA-Live-Structure/2.0",Accept:"application/json"};
async function yahoo(interval:string,range:string,prepost=true){const u=new URL("https://query1.finance.yahoo.com/v8/finance/chart/NVDA");u.searchParams.set("interval",interval);u.searchParams.set("range",range);u.searchParams.set("includePrePost",String(prepost));const r=await fetch(u,{headers,cache:"no-store"});if(!r.ok)throw new Error("public feed failed");const j=await r.json() as {chart?:{result?:Chart[]}};const x=j.chart?.result?.[0];if(!x)throw new Error("empty feed");return x}
function ny(epoch:number){return Object.fromEntries(new Intl.DateTimeFormat("en-US",{timeZone:"America/New_York",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).formatToParts(new Date(epoch*1000)).map(p=>[p.type,p.value]))}
function valid(v:unknown):v is number{return typeof v==="number"&&Number.isFinite(v)}
function sessionLabel(){const p=ny(Date.now()/1000),n=Number(p.hour)*60+Number(p.minute);return n<240?"CLOSED":n<570?"PREMARKET":n<960?"MARKET OPEN":n<1200?"AFTER-HOURS":"CLOSED"}

async function massiveToday(key:string){const date=new Intl.DateTimeFormat("en-CA",{timeZone:"America/New_York",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());const base="https://api.massive.com";const [aggR,lastR]=await Promise.all([fetch(`${base}/v2/aggs/ticker/NVDA/range/1/minute/${date}/${date}?adjusted=true&sort=asc&limit=50000&apiKey=${encodeURIComponent(key)}`,{cache:"no-store"}),fetch(`${base}/v2/last/trade/NVDA?apiKey=${encodeURIComponent(key)}`,{cache:"no-store"})]);if(!aggR.ok||!lastR.ok)throw new Error("Massive feed unavailable");const agg=await aggR.json() as {results?:Array<{t:number;o:number;h:number;l:number;c:number;v:number}>};const last=await lastR.json() as {results?:{p?:number;t?:number}};return{bars:(agg.results??[]).map(x=>({time:x.t,open:x.o,high:x.h,low:x.l,close:x.c,volume:x.v})),price:last.results?.p??agg.results?.at(-1)?.c??null,asOf:last.results?.t?new Date(last.results.t/1e6).toISOString():new Date().toISOString()}}

export async function GET(){try{const key=(globalThis as unknown as {process?:{env?:Record<string,string>}}).process?.env?.MASSIVE_API_KEY;const [dailyChart,minuteChart]=await Promise.all([yahoo("1d","1mo",false),yahoo("1m","1d",true)]);const dq=dailyChart.indicators?.quote?.[0],mq=minuteChart.indicators?.quote?.[0];const daily=(dailyChart.timestamp??[]).map((t,i)=>({date:new Intl.DateTimeFormat("en-US",{timeZone:"America/New_York",month:"short",day:"2-digit"}).format(new Date(t*1000)),high:dq?.high?.[i],low:dq?.low?.[i],close:dq?.close?.[i]})).filter((x):x is {date:string;high:number;low:number;close:number}=>valid(x.high)&&valid(x.low)&&valid(x.close)).slice(-10);let bars=(minuteChart.timestamp??[]).map((t,i)=>({time:t*1000,open:mq?.open?.[i],high:mq?.high?.[i],low:mq?.low?.[i],close:mq?.close?.[i],volume:mq?.volume?.[i]??0})).filter((x):x is {time:number;open:number;high:number;low:number;close:number;volume:number}=>valid(x.open)&&valid(x.high)&&valid(x.low)&&valid(x.close));let price=minuteChart.meta?.regularMarketPrice??bars.at(-1)?.close??null,asOf=bars.length?new Date(bars.at(-1)!.time).toISOString():new Date().toISOString(),source="Public consolidated feed · may be delayed",realtime=false;if(key){try{const live=await massiveToday(key);if(live.bars.length)bars=live.bars;if(valid(live.price))price=live.price;asOf=live.asOf;source="Massive SIP consolidated trades";realtime=true}catch{/* keep resilient public fallback */}}const parts=bars.map(b=>({b,p:ny(b.time/1000)})),today=parts.at(-1)?.p;const same=(p:Record<string,string>)=>p.year===today?.year&&p.month===today?.month&&p.day===today?.day;const pre=parts.filter(({p})=>same(p)&&(Number(p.hour)<9||(Number(p.hour)===9&&Number(p.minute)<30))).map(x=>x.b),regular=parts.filter(({p})=>same(p)&&((Number(p.hour)===9&&Number(p.minute)>=30)||(Number(p.hour)>9&&Number(p.hour)<16))).map(x=>x.b),first=parts.find(({p})=>same(p)&&Number(p.hour)===9&&Number(p.minute)===30)?.b;return Response.json({symbol:"NVDA",price,previousClose:daily.at(-2)?.close??minuteChart.meta?.chartPreviousClose??minuteChart.meta?.previousClose??null,asOf,session:sessionLabel(),source,realtime,bars,daily,day:{open:regular.at(0)?.open??bars.at(0)?.open??null,high:regular.length?Math.max(...regular.map(x=>x.high)):bars.length?Math.max(...bars.map(x=>x.high)):null,low:regular.length?Math.min(...regular.map(x=>x.low)):bars.length?Math.min(...bars.map(x=>x.low)):null,volume:regular.reduce((s,x)=>s+x.volume,0)},premarket:{high:pre.length?Math.max(...pre.map(x=>x.high)):null,low:pre.length?Math.min(...pre.map(x=>x.low)):null,volume:pre.reduce((s,x)=>s+x.volume,0)},firstMinute:{close:first?.close??null,volume:first?.volume??0}},{headers:{"Cache-Control":"no-store, no-cache, must-revalidate","CDN-Cache-Control":"no-store"}})}catch(e){return Response.json({error:"Market data unavailable",detail:e instanceof Error?e.message:"unknown"},{status:503,headers:{"Cache-Control":"no-store"}})}}
