type Quote={high?:Array<number|null>;low?:Array<number|null>;open?:Array<number|null>;close?:Array<number|null>;volume?:Array<number|null>};
type Chart={meta?:{regularMarketPrice?:number;previousClose?:number;chartPreviousClose?:number};timestamp?:number[];indicators?:{quote?:Quote[]}};
type Bar={time:number;open:number;high:number;low:number;close:number;volume:number};
const headers={"User-Agent":"Mozilla/5.0 NVDA-Live-Structure/3.0",Accept:"application/json"};
const etDate=(d:Date)=>new Intl.DateTimeFormat("en-CA",{timeZone:"America/New_York",year:"numeric",month:"2-digit",day:"2-digit"}).format(d);
const displayDate=(d:Date)=>new Intl.DateTimeFormat("en-US",{timeZone:"America/New_York",month:"short",day:"2-digit"}).format(d);

async function yahoo(interval:string,range:string,prepost=true){const u=new URL("https://query1.finance.yahoo.com/v8/finance/chart/NVDA");u.searchParams.set("interval",interval);u.searchParams.set("range",range);u.searchParams.set("includePrePost",String(prepost));const r=await fetch(u,{headers,cache:"no-store"});if(!r.ok)throw new Error("public feed failed");const j=await r.json() as {chart?:{result?:Chart[]}};const x=j.chart?.result?.[0];if(!x)throw new Error("empty feed");return x}
let historyCache:{expires:number;daily:Chart;minute:Chart}|null=null;
async function marketHistory(){if(historyCache&&historyCache.expires>Date.now())return historyCache;const[daily,minute]=await Promise.all([yahoo("1d","1mo",false),yahoo("1m","5d",true)]);historyCache={expires:Date.now()+60_000,daily,minute};return historyCache}
function ny(epoch:number){return Object.fromEntries(new Intl.DateTimeFormat("en-US",{timeZone:"America/New_York",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).formatToParts(new Date(epoch*1000)).map(p=>[p.type,p.value]))}
function valid(v:unknown):v is number{return typeof v==="number"&&Number.isFinite(v)}
const keyFromParts=(p:Record<string,string>)=>`${p.year}-${p.month}-${p.day}`;
function observedFixed(year:number,month:number,day:number){const d=new Date(Date.UTC(year,month,day)),w=d.getUTCDay();if(w===6)d.setUTCDate(d.getUTCDate()-1);if(w===0)d.setUTCDate(d.getUTCDate()+1);return d.toISOString().slice(0,10)}
function nthWeekday(year:number,month:number,weekday:number,n:number){const d=new Date(Date.UTC(year,month,1));d.setUTCDate(1+(7+weekday-d.getUTCDay())%7+(n-1)*7);return d.toISOString().slice(0,10)}
function lastWeekday(year:number,month:number,weekday:number){const d=new Date(Date.UTC(year,month+1,0));d.setUTCDate(d.getUTCDate()-(7+d.getUTCDay()-weekday)%7);return d.toISOString().slice(0,10)}
function easterSunday(year:number){const a=year%19,b=Math.floor(year/100),c=year%100,d=Math.floor(b/4),e=b%4,f=Math.floor((b+8)/25),g=Math.floor((b-f+1)/3),h=(19*a+b-d-g+15)%30,i=Math.floor(c/4),k=c%4,l=(32+2*e+2*i-h-k)%7,m=Math.floor((a+11*h+22*l)/451),month=Math.floor((h+l-7*m+114)/31)-1,day=(h+l-7*m+114)%31+1;return new Date(Date.UTC(year,month,day))}
function marketHoliday(key:string){const year=Number(key.slice(0,4)),goodFriday=easterSunday(year);goodFriday.setUTCDate(goodFriday.getUTCDate()-2);return new Set([observedFixed(year,0,1),observedFixed(year+1,0,1),nthWeekday(year,0,1,3),nthWeekday(year,1,1,3),goodFriday.toISOString().slice(0,10),lastWeekday(year,4,1),observedFixed(year,5,19),observedFixed(year,6,4),nthWeekday(year,8,1,1),nthWeekday(year,10,4,4),observedFixed(year,11,25)]).has(key)}
function targetSessionDate(){const p=ny(Date.now()/1000),minute=Number(p.hour)*60+Number(p.minute),d=new Date(Date.UTC(Number(p.year),Number(p.month)-1,Number(p.day)));if(minute>=960)d.setUTCDate(d.getUTCDate()+1);while(d.getUTCDay()===0||d.getUTCDay()===6||marketHoliday(d.toISOString().slice(0,10)))d.setUTCDate(d.getUTCDate()+1);return d.toISOString().slice(0,10)}
function sessionLabel(){const p=ny(Date.now()/1000),n=Number(p.hour)*60+Number(p.minute);return n<240?"CLOSED":n<570?"PREMARKET":n<960?"MARKET OPEN":n<1200?"AFTER-HOURS":"CLOSED"}
function chartBars(chart:Chart){const q=chart.indicators?.quote?.[0];return(chart.timestamp??[]).map((t,i)=>({time:t*1000,open:q?.open?.[i],high:q?.high?.[i],low:q?.low?.[i],close:q?.close?.[i],volume:q?.volume?.[i]??0})).filter((x):x is Bar=>valid(x.open)&&valid(x.high)&&valid(x.low)&&valid(x.close))}

// The key stays server-side; browser clients receive only normalized NVDA data.
type FinnhubQuote={c?:number;h?:number;l?:number;o?:number;pc?:number;t?:number};
async function finnhubQuote(key:string){const r=await fetch("https://finnhub.io/api/v1/quote?symbol=NVDA",{headers:{"X-Finnhub-Token":key,Accept:"application/json"},cache:"no-store"});if(!r.ok)throw new Error(`Finnhub quote failed (${r.status})`);const q=await r.json() as FinnhubQuote;if(!valid(q.c)||q.c<=0)throw new Error("Finnhub returned no NVDA quote");return q}

export async function GET(){try{
 const finnhubKey=(globalThis as unknown as {process?:{env?:Record<string,string>}}).process?.env?.FINNHUB_API_KEY,targetDate=targetSessionDate(),todayKey=etDate(new Date());
 const history=await marketHistory(),dailyChart=history.daily,minuteChart=history.minute;
 const dq=dailyChart.indicators?.quote?.[0];
 const daily=(dailyChart.timestamp??[]).map((t,i)=>({date:displayDate(new Date(t*1000)),dateKey:etDate(new Date(t*1000)),high:dq?.high?.[i],low:dq?.low?.[i],close:dq?.close?.[i]})).filter((x):x is {date:string;dateKey:string;high:number;low:number;close:number}=>x.dateKey<targetDate&&valid(x.high)&&valid(x.low)&&valid(x.close)).slice(-10).map(({date,high,low,close})=>({date,high,low,close}));
 const historicalBars=chartBars(minuteChart),historicalParts=historicalBars.map(b=>({b,p:ny(b.time/1000)}));
 const firstMinuteHistory=historicalParts.filter(({p})=>keyFromParts(p)<targetDate&&Number(p.hour)===9&&Number(p.minute)===30).slice(-10).map(({b,p})=>({date:keyFromParts(p),range:b.high-b.low,volume:b.volume,close:b.close}));
 let price=minuteChart.meta?.regularMarketPrice??historicalBars.at(-1)?.close??null,asOf=historicalBars.length?new Date(historicalBars.at(-1)!.time).toISOString():new Date().toISOString(),source="Public consolidated feed · may be delayed",realtime=false,liveQuote:FinnhubQuote|null=null;
 if(finnhubKey){try{liveQuote=await finnhubQuote(finnhubKey);price=liveQuote.c!;asOf=liveQuote.t?new Date(liveQuote.t*1000).toISOString():new Date().toISOString();source="Finnhub real-time NVDA quote";realtime=true}catch{/* resilient public fallback */}}
 const parts=historicalBars.map(b=>({b,p:ny(b.time/1000),date:keyFromParts(ny(b.time/1000))}));
 const targetBars=parts.filter(x=>x.date===targetDate),latestDate=parts.at(-1)?.date,displayBars=(targetBars.length?targetBars:parts.filter(x=>x.date===latestDate)).map(x=>x.b);
 const pre=targetBars.filter(({p})=>Number(p.hour)<9||(Number(p.hour)===9&&Number(p.minute)<30)).map(x=>x.b),regular=targetBars.filter(({p})=>(Number(p.hour)===9&&Number(p.minute)>=30)||(Number(p.hour)>9&&Number(p.hour)<16)).map(x=>x.b),first=targetBars.find(({p})=>Number(p.hour)===9&&Number(p.minute)===30)?.b;
 const session=sessionLabel(),quoteDay=targetDate===todayKey&&session==="MARKET OPEN"&&liveQuote;
 return Response.json({symbol:"NVDA",targetDate,price,previousClose:daily.at(-1)?.close??liveQuote?.pc??minuteChart.meta?.chartPreviousClose??minuteChart.meta?.previousClose??null,asOf,session,source,realtime,bars:displayBars,daily,firstMinuteHistory,day:{open:quoteDay&&valid(liveQuote?.o)?liveQuote!.o!:regular.at(0)?.open??null,high:quoteDay&&valid(liveQuote?.h)?liveQuote!.h!:regular.length?Math.max(...regular.map(x=>x.high)):null,low:quoteDay&&valid(liveQuote?.l)?liveQuote!.l!:regular.length?Math.min(...regular.map(x=>x.low)):null,volume:regular.reduce((s,x)=>s+x.volume,0)},premarket:{high:pre.length?Math.max(...pre.map(x=>x.high)):null,low:pre.length?Math.min(...pre.map(x=>x.low)):null,current:targetDate===todayKey&&session==="PREMARKET"&&liveQuote?liveQuote.c:pre.at(-1)?.close??null,volume:pre.reduce((s,x)=>s+x.volume,0)},firstMinute:{close:first?.close??null,high:first?.high??null,low:first?.low??null,volume:first?.volume??0}},{headers:{"Cache-Control":"no-store, no-cache, must-revalidate","CDN-Cache-Control":"no-store"}})
}catch(e){return Response.json({error:"Market data unavailable",detail:e instanceof Error?e.message:"unknown"},{status:503,headers:{"Cache-Control":"no-store"}})}}
